# Base Image
FROM node:16-alpine

# Working Dir
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Install 
COPY --chown=node:node ./package.json ./
RUN npm install

# Copy All file
COPY --chown=node:node ./ ./

# Start Dev Server
CMD ["npm", "start"]