language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t manojjonam/testcontainer -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true manojjonam/testcontainer npm test

after_success:
  - echo "$DOCKERHUB_PWD" | docker login -u "$DOCKER_USR" --password-stdin
  - docker build -t manojjonam/multi-client1 ./client
  - docker build -t manojjonam/multi-nginx1 ./nginx
  - docker build -t manojjonam/multi-server1 ./server
  - docker build -t manojjonam/multi-worker1 ./worker
  - docker push manojjonam/multi-client1
  - docker push manojjonam/multi-nginx1
  - docker push manojjonam/multi-server1
  - docker push manojjonam/multi-worker1